#!/usr/bin/env node
// Seven‑OS Sector‑Aware Autosorter (v3 - Hardened ESM Edition)
// Moves files into correct global sectors safely based on autoscan classification.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = process.cwd();

/**
 * Safely loads the latest autoscan dataset in memory
 */
function getAutoscanDataset() {
  // Check common report locations generated by your system architecture
  const possiblePaths = [
    path.join(ROOT, "seven-os", "system-sync-report.json"),
    path.join(ROOT, "reports", "autoscan-latest.json")
  ];

  for (const p of possiblePaths) {
    if (fs.existsSync(p)) {
      try {
        const data = JSON.parse(fs.readFileSync(p, "utf8"));
        // Handle reports wrapped inside different nesting schemas
        if (data.groups && data.groups.sector) return data.groups;
        if (data.sector) return data;
      } catch (e) {
        console.log(`⚠ Failed parsing data at: ${p}`);
      }
    }
  }

  // Emergency localized map block if external JSON reports are locked by file tasks
  console.log("⚠ [Autosorter Note] External scan files unreadable. Falling back to inline domain matrix tables.");
  return {
    sector: [
      { file: "agriculture.json", sector: "agriculture", target: "seven-os/agriculture" },
      { file: "bridges-tunnels.json", sector: "roads", target: "seven-os/roads" },
      { file: "telecom-infra.json", sector: "telecom", target: "seven-os/telecom" },
      { file: "state.js", sector: "runtime", target: "runtime" }
    ]
  };
}

const autoscan = getAutoscanDataset();

/**
 * Core filesystem execution block with path validation
 */
function moveFile(srcRel, destRel) {
  const src = path.join(ROOT, srcRel);
  const dest = path.join(ROOT, destRel);

  if (!fs.existsSync(src)) {
    return; // File already organized or shifted by parallel execution tracks
  }

  // Prevent circular moving loops from shredding deep code sectors
  if (src === dest) return;

  fs.mkdirSync(path.dirname(dest), { recursive: true });
  console.log(`  🔀 Realigned Asset: ${srcRel} ➔ ${destRel}`);
  
  try {
    fs.renameSync(src, dest);
  } catch (err) {
    console.error(`  ❌ Failed execution path shift on ${srcRel}:`, err.message);
  }
}

async function run() {
  console.log("==================================================");
  console.log("📦   SEVEN-OS SECTOR AUTOSORTER (V3 PRO)          ");
  console.log("==================================================");
  console.log(`Active Corporate Workspace Root: ${ROOT}\n`);

  if (!autoscan || !autoscan.sector) {
    console.error("❌ Mapped structural data fields are unavailable.");
    process.exit(1);
  }

  // Safe file translation loop protecting base directory frameworks
  autoscan.sector.forEach(entry => {
    const { file, sector, target } = entry;
    
    // Ignore files already sitting inside their home directories
    if (file.includes(`/${sector}/`) || file.includes('seven-os/sectors/')) return;

    const baseName = path.basename(file);
    
    // Hardened path alignment rules: place files directly into their manifest-defined homes
    const fallbackTargetFolder = target || `seven-os/sectors/${sector}`;
    const destinationPathString = path.join(fallbackTargetFolder, baseName).replace(/\\/g, "/");

    moveFile(file, destinationPathString);
  });

  console.log("\n==================================================");
  console.log("✅ SECTOR AUTOSORT COMPLETE: All workspace items are inline.");
  console.log("==================================================");
}

run().catch(console.error);

