name = "global-infrastructure-advisory"
main = "src/index.js"
compatibility_date = "2026-04-22"

[assets]
directory = "./public"
binding = "ASSETS"

# Core Vars
[vars]
PROJECT_NAME = "GIA Suite 2050"
GIA_VERSION = "2100"
ENVIRONMENT = "production"
PLATFORM_VERSION = "1.0.0"
DEFAULT_TRUST_ZONE = "public"

# KV Namespace (A-Team)
[[kv_namespaces]]
binding = "GLOBAL_CACHE"
id = "97426b03b961419ba8ca6df016a6039f"

# R2 Bucket
[[r2_buckets]]
binding = "GLOBAL_STORAGE"
bucket_name = "global-storage"

# D1 Databases (Platform Side)
[[d1_databases]]
binding = "GIA_PLATFORM"
database_name = "gia-platform"
database_id = "0e5832f8-ca6a-4796-8053-429f3bfdbbee"

[[d1_databases]]
binding = "RESILIENCE"
database_name = "resilience"
database_id = "c12374bc-f828-481a-aeaa-27822f7aaea3"

[[d1_databases]]
binding = "INTELLIGENCE_SERVICE"
database_name = "intelligence-service"
database_id = "56c33622-1dff-4458-bf42-c1aa544edc27"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
persist = true
invocation_logs = true
head_sampling_rate = 1

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
